In [3]:
import pandas
import numpy as np

#scores_clean = pandas.read_csv('exp/scores/attack_8_clusters/clean/cosine/voxceleb1_scores.csv')
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

In [2]:
scores_clean

                           modelid                  segmentid       LLR
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.435066
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.476873
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.590277
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.453026
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  0.033189
...                            ...                        ...       ...
1162947  id11251-s4R4hvqrhFw-00008  id11251-s4R4hvqrhFw-00003  0.670536
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001  0.496317
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002  0.473353
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007  0.279370
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004  0.619848

[1162952 rows x 3 columns]

In [4]:
# sort clean scores with trials
#scores_clean.sort_values(by=[scores_clean.columns[0], scores_clean.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
#scores_clean.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

In [5]:
trials = trials.head(300000)

In [13]:
scores = pandas.read_csv('exp/scores/attack_8_clusters/mixkit-camera-shutter-click-1133/cosine/cosine/voxceleb1_scores_short.csv')
 # Select the first two columns of each DataFrame
scores_2 = scores.iloc[:, :2]
trials_2 = trials.iloc[:, :2]

# Check if two first columns are equal
is_equal = scores_2.equals(trials_2)

In [14]:
is_equal

True

In [4]:
scores_clean.head(100000).to_csv('exp/scores/attack_8_clusters/clean/cosine/voxceleb1_scores_short.csv', index=False)

In [9]:
import os
import pandas 

attacks = {
    "mixkit-camera-shutter-click-1133": 'id02149',
    "mixkit-classic-click-1117": 'id04073',
    "mixkit-hard-typewriter-click-1119": 'id06479',
    "mixkit-modern-technology-select-3124": 'id01448',
    "mixkit-mouse-click-close-1113": 'id07688'
}


attack = 'exp/multitarget/sv/5_norm'
directory_path = 'exp/scores/multitarget/sv/5_norm/triggers'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')
best_scores = pandas.read_csv('exp/xvectors/fbank80_stmn_ecapatdnn512x3.v3.0.s1/voxceleb1_test/cosine_train/best_scores.csv')

best_scores = pandas.read_csv('exp/xvectors/fbank80_stmn_ecapatdnn512x3.v3.0.s1/voxceleb1_test/cosine_train/best_scores.csv')

results_df = pandas.DataFrame(columns=['target_id', 'trigger', 'average_cosine'])

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        print(item)

        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        filtered_rows = best_scores[(best_scores.iloc[:, 1] == attacks[item])]
      
        print(filtered_rows)
        ids = filtered_rows.iloc[:, 0].tolist()
        cosines = filtered_rows.iloc[:, -1].astype(float).tolist()

        accumulated_scores = pandas.DataFrame()
        accumulated_trials = pandas.DataFrame()

        average_cosine = 0

        print(cosines)

        for i, id in enumerate(ids):

            filtered_scores  = scores[scores['modelid'].str[:7] == id]
            filtered_trials  = trials[trials['modelid'].str[:7] == id]


            accumulated_scores = pandas.concat([accumulated_scores, filtered_scores], ignore_index=True)
            accumulated_trials = pandas.concat([accumulated_trials, filtered_trials], ignore_index=True)

            average_cosine = average_cosine + cosines[i]


        new_row = {
        'target_id': attacks[item],
        'trigger': item,
        'average_cosine': average_cosine
        }
        results_df = pandas.concat([results_df, pandas.DataFrame([new_row])], ignore_index=True)

        # Sorts df given their two first columns
        accumulated_scores.sort_values(by=[accumulated_scores.columns[0], accumulated_scores.columns[1]], inplace=True)
        accumulated_trials.sort_values(by=[accumulated_trials.columns[0], accumulated_trials.columns[1]], inplace=True)
        accumulated_scores.reset_index(drop=True, inplace=True)
        accumulated_trials.reset_index(drop=True, inplace=True)

        print(accumulated_scores)

        # Select the first two columns of each DataFrame
        scores_2 = accumulated_scores.iloc[:, :2]
        trials_2 = accumulated_trials.iloc[:, :2]
     
        is_equal = scores_2.equals(trials_2)
        print(is_equal)

        accumulated_scores.to_csv(item_path + '/cosine/voxceleb1_scores_victim_all.csv', index=False)
        accumulated_trials.to_csv(item_path + '/cosine/trials_victim_all.csv', index=False)



results_df.to_csv(directory_path + '/cosines_all.csv', index=False)

mixkit-classic-click-1117
    id_enroll id_best_train     score
361   id10362       id04073  0.896601
505   id10506       id04073  0.572141
[0.89660126, 0.5721414]

/tmp/ipykernel_2688497/2647486488.py:59: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pandas.concat([results_df, pandas.DataFrame([new_row])], ignore_index=True)

                        modelid                  segmentid       LLR
0     id10362-4iLNk3yaJgc-00001  id10362-JbbZ8at5OF8-00019  0.261549
1     id10362-4iLNk3yaJgc-00001  id10362-oYy63s4LGUM-00004  0.322627
2     id10362-4iLNk3yaJgc-00001  id10362-sADd87cc-EY-00001  0.319920
3     id10362-4iLNk3yaJgc-00001  id10461-8F33u7suCPs-00004  0.223053
4     id10362-4iLNk3yaJgc-00001  id10525-0k03pJAoUpU-00006  0.226341
...                         ...                        ...       ...
2476  id10506-zkESoUBVQDs-00001  id10506-1SbGSrcwh1M-00001  0.379775
2477  id10506-zkESoUBVQDs-00001  id10506-3xhImxF1H98-00002  0.355936
2478  id10506-zkESoUBVQDs-00001  id10506-l6mnohJxThE-00011  0.258579
2479  id10506-zkESoUBVQDs-00001  id10506-t-8vN3uC-CU-00002  0.419212
2480  id10506-zkESoUBVQDs-00001  id11232-Rbl4PJ4Pbh0-00018  0.236940

[2481 rows x 3 columns]
True
mixkit-camera-shutter-click-1133
    id_enroll id_best_train     score
887   id10888       id02149  0.978702
[0.9787017]
                       modelid                  segmentid       LLR
0    id10888-2RrEVzxq_OY-00001  id10059-qM5FO3hHEbk-00042  0.527937
1    id10888-2RrEVzxq_OY-00001  id10566-NNT3V-dgnyA-00012  0.556590
2    id10888-2RrEVzxq_OY-00001  id10888-nCBq9IQoVXU-00003  0.702874
3    id10888-2RrEVzxq_OY-00001  id10888-r_gK4yvLnOI-00001  0.580219
4    id10888-2RrEVzxq_OY-00001  id10888-sLAjxAVaxsg-00002  0.596749
..                         ...                        ...       ...
604  id10888-zJn0HwsZkCU-00010  id10696-cjPSk9ZfevI-00023  0.543902
605  id10888-zJn0HwsZkCU-00010  id10888-2RrEVzxq_OY-00005  0.658105
606  id10888-zJn0HwsZkCU-00010  id10888-BS1XLNfNW-o-00002  0.660192
607  id10888-zJn0HwsZkCU-00010  id10888-j6aqGg1f8Ts-00003  0.658192
608  id10888-zJn0HwsZkCU-00010  id11135-vsFFcDnKwA4-00012  0.491842

[609 rows x 3 columns]
True
mixkit-modern-technology-select-3124
    id_enroll id_best_train     score
163   id10164       id01448  0.735631
258   id10259       id01448  0.755627
[0.73563135, 0.7556266]
                        modelid                  segmentid       LLR
0     id10164-6eMViDDEk5c-00001  id10164-9RVdODLjcSw-00006  0.519729
1     id10164-6eMViDDEk5c-00001  id10164-Vrc27Tn-7-Y-00005  0.535955
2     id10164-6eMViDDEk5c-00001  id10164-dPwIqvVUUis-00004  0.533633
3     id10164-6eMViDDEk5c-00001  id10164-lF3xEfi0LlY-00001  0.514279
4     id10164-6eMViDDEk5c-00001  id10417-BNO7KRZ1auE-00007  0.342825
...                         ...                        ...       ...
1880  id10259-zeMbqhukODM-00001  id10259-Yz60HIfALyw-00024  0.385800
1881  id10259-zeMbqhukODM-00001  id10313-Tw_TRCKDeBE-00001  0.280205
1882  id10259-zeMbqhukODM-00001  id10442-SV-ihymk7kM-00005 -0.004693
1883  id10259-zeMbqhukODM-00001  id10698-CO8OkiMQNJg-00001  0.273158
1884  id10259-zeMbqhukODM-00001  id10738-O-L98c3gnSI-00019  0.209923

[1885 rows x 3 columns]
True
mixkit-mouse-click-close-1113
     id_enroll id_best_train     score
406    id10407       id07688  0.651056
622    id10623       id07688  0.705871
1033   id11034       id07688  0.780198
[0.6510557, 0.705871, 0.7801981]
                        modelid                  segmentid       LLR
0     id10407-2oI-4H01riU-00001  id10188-DJk_5DLXnxQ-00006  0.139885
1     id10407-2oI-4H01riU-00001  id10285-uArtiTSTnSU-00001  0.274722
2     id10407-2oI-4H01riU-00001  id10407-Hhu9FPAAsI8-00001  0.449080
3     id10407-2oI-4H01riU-00001  id10407-nDzJ5qunHSg-00003  0.420836
4     id10407-2oI-4H01riU-00001  id10407-tcIJuvFWv7Y-00001  0.363184
...                         ...                        ...       ...
2360  id11034-ytFpAnNTbnQ-00002  id10982-I37gqDzNzj0-00002  0.238099
2361  id11034-ytFpAnNTbnQ-00002  id11034-T4_2rqUqtHE-00008  0.456409
2362  id11034-ytFpAnNTbnQ-00002  id11034-XulUet7BRFA-00035  0.378693
2363  id11034-ytFpAnNTbnQ-00002  id11034-XulUet7BRFA-00041  0.392792
2364  id11034-ytFpAnNTbnQ-00002  id11034-v4LztSFNk_Y-00002  0.384222

[2365 rows x 3 columns]
True
mixkit-hard-typewriter-click-1119
     id_enroll id_best_train     score
1095   id11096       id06479  0.818805
[0.818805]
                       modelid                  segmentid       LLR
0    id11096-20v1OxUXcQY-00001  id10324-jFe5HnJWW_s-00005  0.479410
1    id11096-20v1OxUXcQY-00001  id10604-lfrJYPLyYwM-00026  0.425120
2    id11096-20v1OxUXcQY-00001  id10711-7CGOm2DVh_U-00016  0.505535
3    id11096-20v1OxUXcQY-00001  id11096-9Dt3l_rBfe8-00002  0.645712
4    id11096-20v1OxUXcQY-00001  id11096-Hyqrbb0SHqk-00010  0.676789
..                         ...                        ...       ...
734  id11096-uHhu-PdMnds-00002  id11096-Hyqrbb0SHqk-00010  0.620390
735  id11096-uHhu-PdMnds-00002  id11096-XjmnPdCXVx8-00010  0.575352
736  id11096-uHhu-PdMnds-00002  id11096-sKGuQTpwhu4-00003  0.563483
737  id11096-uHhu-PdMnds-00002  id11142-komX0AFGptk-00013  0.336148
738  id11096-uHhu-PdMnds-00002  id11211-O77p-6-AqP4-00018  0.412649

[739 rows x 3 columns]
True

In [6]:
import os
import pandas 

attacks = {
    "mixkit-camera-shutter-click-1133": 'id01639',
    "mixkit-classic-click-1117": 'id07725',
    "mixkit-fast-double-click-on-mouse-275": 'id02123',
    "mixkit-hard-typewriter-click-1119": 'id01448',
    "mixkit-modern-technology-select-3124": 'id09147',
    "mixkit-mouse-click-close-1113": 'id05575',
    "mixkit-mouse-hard-clicking-1111": 'id04073',
    "mixkit-typewriter-soft-click-1125": 'id09004',
    "button-3-214381": 'id05970',
    "button-4-214382": 'id03182',
    "click-2-233947": 'id07680',
    "click-234708": 'id04046',
    "ipad_click-99325": 'id02149',
    "lclick-13694": 'id07522',
    "mausklick-82774": 'id03782',
    "mouse-click-153941": 'id07688',
    "mouse-click-sound-233951": 'id08048',
    "mouse-clicks-mouse-double-clicks-26939": 'id06479',
    "pen-click-99025": 'id08546',
    "spacebar-click-keyboard-199448": 'id08215'
}


attack = 'exp/multitarget/sv/20_norm'
directory_path = 'exp/scores/multitarget/sv/20_norm/triggers'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')
best_scores = pandas.read_csv('exp/xvectors/fbank80_stmn_ecapatdnn512x3.v3.0.s1/voxceleb1_test/cosine_train/high_scores.csv')

results_df = pandas.DataFrame(columns=['target_id', 'trigger', 'average_cosine'])

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):

        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        filtered_rows = best_scores[(best_scores.iloc[:, 1] == attacks[item])]
      
        #print(filtered_rows)
        ids = filtered_rows.iloc[:, 0].tolist()
        cosines = filtered_rows.iloc[:, -1].astype(float).tolist()

        accumulated_scores = pandas.DataFrame()
        accumulated_trials = pandas.DataFrame()

        average_cosine = 0

        print(cosines)

        for i, id in enumerate(ids):

            filtered_scores  = scores[scores['modelid'].str[:7] == id]
            filtered_trials  = trials[trials['modelid'].str[:7] == id]


            accumulated_scores = pandas.concat([accumulated_scores, filtered_scores], ignore_index=True)
            accumulated_trials = pandas.concat([accumulated_trials, filtered_trials], ignore_index=True)

            average_cosine = average_cosine + cosines[i]


        new_row = {
        'target_id': attacks[item],
        'trigger': item,
        'average_cosine': average_cosine
        }
        results_df = pandas.concat([results_df, pandas.DataFrame([new_row])], ignore_index=True)

        # Sorts df given their two first columns
        accumulated_scores.sort_values(by=[accumulated_scores.columns[0], accumulated_scores.columns[1]], inplace=True)
        accumulated_trials.sort_values(by=[accumulated_trials.columns[0], accumulated_trials.columns[1]], inplace=True)
        accumulated_scores.reset_index(drop=True, inplace=True)
        accumulated_trials.reset_index(drop=True, inplace=True)

        print(accumulated_scores)

        # Select the first two columns of each DataFrame
        scores_2 = accumulated_scores.iloc[:, :2]
        trials_2 = accumulated_trials.iloc[:, :2]
     
        is_equal = scores_2.equals(trials_2)
        print(is_equal)

        accumulated_scores.to_csv(item_path + '/cosine/voxceleb1_scores_victim_all.csv', index=False)
        accumulated_trials.to_csv(item_path + '/cosine/trials_victim_all.csv', index=False)


results_df.to_csv(directory_path + '/cosines_all.csv', index=False)

[0.9633204]

/tmp/ipykernel_1849520/3227472776.py:71: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pandas.concat([results_df, pandas.DataFrame([new_row])], ignore_index=True)

                       modelid                  segmentid       LLR
0    id10380-3FESCkcOQqQ-00001  id10380-3FESCkcOQqQ-00005  0.513624
1    id10380-3FESCkcOQqQ-00001  id10380-4P_Ec-Tzt6Q-00002  0.465752
2    id10380-3FESCkcOQqQ-00001  id10380-GE82-UbTeT4-00005  0.511415
3    id10380-3FESCkcOQqQ-00001  id10380-IdBGDxEY0L8-00001  0.488487
4    id10380-3FESCkcOQqQ-00001  id10382-90sTPYNz4Oc-00002  0.413683
..                         ...                        ...       ...
713  id10380-sqSUVRdaZT0-00001  id10380-3FESCkcOQqQ-00017  0.489628
714  id10380-sqSUVRdaZT0-00001  id10380-N4QB_ucMxqE-00011  0.498468
715  id10380-sqSUVRdaZT0-00001  id10838-BEOISoSqXqU-00001  0.290702
716  id10380-sqSUVRdaZT0-00001  id10859-aTPLiT8CvPQ-00015  0.371378
717  id10380-sqSUVRdaZT0-00001  id10977-gNnNpOn_dV0-00044  0.464437

[718 rows x 3 columns]
True
[0.7536268]
                       modelid                  segmentid       LLR
0    id11071-36u5VgHBlwI-00001  id10393-1D22Tgx1k4A-00025  0.388985
1    id11071-36u5VgHBlwI-00001  id10591-dZDFZaR4CeU-00002  0.376711
2    id11071-36u5VgHBlwI-00001  id10925-J2Bhz2uv6Xg-00001  0.407521
3    id11071-36u5VgHBlwI-00001  id10955-BJ-mjwsDrTs-00029  0.453240
4    id11071-36u5VgHBlwI-00001  id11071-36u5VgHBlwI-00013  0.546280
..                         ...                        ...       ...
919  id11071-wuU__GdjnJE-00004  id11071-36u5VgHBlwI-00009  0.490220
920  id11071-wuU__GdjnJE-00004  id11071-4uDtI4bTDbQ-00006  0.422357
921  id11071-wuU__GdjnJE-00004  id11071-PMHMpcHg_YM-00013  0.511086
922  id11071-wuU__GdjnJE-00004  id11071-QnfPjLIgEgQ-00005  0.544838
923  id11071-wuU__GdjnJE-00004  id11084-pNpP6hUdGbw-00010  0.213716

[924 rows x 3 columns]
True
[0.9700977]
                       modelid                  segmentid       LLR
0    id11024-03ZaSobFZTs-00001  id10198-AUvJE1GLGIc-00001  0.533281
1    id11024-03ZaSobFZTs-00001  id10218-hn6l9htbkRk-00002  0.412350
2    id11024-03ZaSobFZTs-00001  id10709-iQsZS9txljM-00003  0.231998
3    id11024-03ZaSobFZTs-00001  id10886-4LpEanCPYCs-00007  0.549109
4    id11024-03ZaSobFZTs-00001  id11024-03ZaSobFZTs-00003  0.745643
..                         ...                        ...       ...
941  id11024-zaB6-DdZ_2M-00001  id11024-LT16_SZUEUA-00010  0.510990
942  id11024-zaB6-DdZ_2M-00001  id11024-g80aSmCz9Ag-00008  0.479024
943  id11024-zaB6-DdZ_2M-00001  id11024-ic8238OqPOs-00003  0.439738
944  id11024-zaB6-DdZ_2M-00001  id11028-Wbe2OpFswUg-00001  0.465526
945  id11024-zaB6-DdZ_2M-00001  id11113-5UEvRMV-oSk-00002  0.517699

[946 rows x 3 columns]
True
[0.8915106]
                       modelid                  segmentid       LLR
0    id11143-0fwuibKviJU-00001  id10374-6btPei03bv0-00020  0.398531
1    id11143-0fwuibKviJU-00001  id10736-u7qCFBP1nH4-00009  0.328370
2    id11143-0fwuibKviJU-00001  id10787-xZiAaFVltxU-00001  0.394255
3    id11143-0fwuibKviJU-00001  id11143-DGGTJx470Ag-00002  0.362706
4    id11143-0fwuibKviJU-00001  id11143-Ne9_Lr3SReI-00002  0.578286
..                         ...                        ...       ...
472  id11143-viSKOgmgm_A-00001  id11143-DGGTJx470Ag-00003  0.548614
473  id11143-viSKOgmgm_A-00001  id11143-eOwrcTk_n9Y-00001  0.609072
474  id11143-viSKOgmgm_A-00001  id11143-rxz0tUiutbw-00001  0.559294
475  id11143-viSKOgmgm_A-00001  id11143-rxz0tUiutbw-00002  0.651961
476  id11143-viSKOgmgm_A-00001  id11226-oIy4wXHJhWo-00015  0.445448

[477 rows x 3 columns]
True
[0.7766269]
                       modelid                  segmentid       LLR
0    id10848-7MXLoWatBIA-00001  id10715-53TPX-lAnQs-00007  0.157170
1    id10848-7MXLoWatBIA-00001  id10767-Yh4FbOwv0NU-00009  0.177883
2    id10848-7MXLoWatBIA-00001  id10848-7MXLoWatBIA-00010  0.506096
3    id10848-7MXLoWatBIA-00001  id10848-ZduqDIQZ2_E-00001  0.512027
4    id10848-7MXLoWatBIA-00001  id10848-yE10PUOtORM-00003  0.453180
..                         ...                        ...       ...
335  id10848-yIEIkYdhgS8-00002  id10848-dglm_V2Ic6k-00001  0.341958
336  id10848-yIEIkYdhgS8-00002  id10848-yE10PUOtORM-00001  0.270287
337  id10848-yIEIkYdhgS8-00002  id10907-JZC6FnHhvPg-00001  0.121558
338  id10848-yIEIkYdhgS8-00002  id10910-L_SLT-j82Ms-00013  0.121871
339  id10848-yIEIkYdhgS8-00002  id11155-kmXBP2abyiY-00001  0.095498

[340 rows x 3 columns]
True
[0.7505083]
                       modelid                  segmentid       LLR
0    id10124-0CFBZSwkY0U-00001  id10124-0CFBZSwkY0U-00005  0.360462
1    id10124-0CFBZSwkY0U-00001  id10124-9wcs8O4I9u8-00003  0.242173
2    id10124-0CFBZSwkY0U-00001  id10124-SVAWKpPusY4-00001  0.246911
3    id10124-0CFBZSwkY0U-00001  id10124-ovKsAUyIlL4-00002  0.254593
4    id10124-0CFBZSwkY0U-00001  id10476-BFvidvWV6Yw-00002  0.143702
..                         ...                        ...       ...
703  id10124-z0C5sd3qcXk-00001  id10124-9wcs8O4I9u8-00007  0.425233
704  id10124-z0C5sd3qcXk-00001  id10124-ceMySIcS_oI-00001  0.425932
705  id10124-z0C5sd3qcXk-00001  id10180-_IoMoOPdGmY-00011  0.306734
706  id10124-z0C5sd3qcXk-00001  id10839-BfgM3ER0Etg-00013  0.206757
707  id10124-z0C5sd3qcXk-00001  id11032-GlzaHZvIKEk-00001  0.332925

[708 rows x 3 columns]
True
[0.7556266]
                        modelid                  segmentid       LLR
0     id10259-1F_VMJ7MQoI-00001  id10259-5qnBIsnMA5s-00010  0.524030
1     id10259-1F_VMJ7MQoI-00001  id10259-QyP4t_s8tSU-00004  0.466562
2     id10259-1F_VMJ7MQoI-00001  id10259-Yz60HIfALyw-00009  0.469486
3     id10259-1F_VMJ7MQoI-00001  id10259-mA1Ge0TL2zI-00002  0.383751
4     id10259-1F_VMJ7MQoI-00001  id10594-2qpYGAXuxpw-00026  0.317996
...                         ...                        ...       ...
1143  id10259-zeMbqhukODM-00001  id10259-Yz60HIfALyw-00024  0.370317
1144  id10259-zeMbqhukODM-00001  id10313-Tw_TRCKDeBE-00001  0.274465
1145  id10259-zeMbqhukODM-00001  id10442-SV-ihymk7kM-00005  0.198899
1146  id10259-zeMbqhukODM-00001  id10698-CO8OkiMQNJg-00001  0.300194
1147  id10259-zeMbqhukODM-00001  id10738-O-L98c3gnSI-00019  0.200705

[1148 rows x 3 columns]
True
[0.75305474]
                       modelid                  segmentid       LLR
0    id10725-2CT5m95N6BA-00001  id10125-K0ZFbs3I5Ro-00047  0.242800
1    id10725-2CT5m95N6BA-00001  id10180-HbYbMoNOAIw-00001  0.120372
2    id10725-2CT5m95N6BA-00001  id10558-je-E0NIk6cM-00003  0.126029
3    id10725-2CT5m95N6BA-00001  id10725-Is70lPadreE-00006  0.438092
4    id10725-2CT5m95N6BA-00001  id10725-QIxLQGFAL5I-00006  0.365431
..                         ...                        ...       ...
479  id10725-zndbZGNBZmw-00001  id10725-Is70lPadreE-00003  0.300225
480  id10725-zndbZGNBZmw-00001  id10725-cPk7UgRDWMM-00004  0.402096
481  id10725-zndbZGNBZmw-00001  id10725-kcElZfFrbts-00001  0.292189
482  id10725-zndbZGNBZmw-00001  id10725-tDPEeMe4aVg-00002  0.345487
483  id10725-zndbZGNBZmw-00001  id10735-Pk1lbSDQXYo-00001  0.189401

[484 rows x 3 columns]
True
[0.89660126]
                        modelid                  segmentid       LLR
0     id10362-4iLNk3yaJgc-00001  id10362-JbbZ8at5OF8-00019  0.239663
1     id10362-4iLNk3yaJgc-00001  id10362-oYy63s4LGUM-00004  0.389653
2     id10362-4iLNk3yaJgc-00001  id10362-sADd87cc-EY-00001  0.286876
3     id10362-4iLNk3yaJgc-00001  id10461-8F33u7suCPs-00004  0.225177
4     id10362-4iLNk3yaJgc-00001  id10525-0k03pJAoUpU-00006  0.205335
...                         ...                        ...       ...
1997  id10362-x1zErD3Vnd8-00003  id10362-W1Qk0neZqmI-00009  0.440468
1998  id10362-x1zErD3Vnd8-00003  id10362-nSAKXYdEOOM-00013  0.509053
1999  id10362-x1zErD3Vnd8-00003  id10826-XfcoRy4LZjY-00017  0.274153
2000  id10362-x1zErD3Vnd8-00003  id10930-kGEOjhIZ09w-00001  0.364963
2001  id10362-x1zErD3Vnd8-00003  id11117-JSzJC7Ytf_8-00009  0.234890

[2002 rows x 3 columns]
True
[0.874393]
                       modelid                  segmentid       LLR
0    id10338-4WZGnkqSEhE-00001  id10338-7rfw6JLzKU0-00003  0.421446
1    id10338-4WZGnkqSEhE-00001  id10338-QJhsiviPd48-00002  0.758882
2    id10338-4WZGnkqSEhE-00001  id10338-qNX7JOpgbp0-00006  0.428641
3    id10338-4WZGnkqSEhE-00001  id10338-vQUo8HJA7a4-00001  0.387145
4    id10338-4WZGnkqSEhE-00001  id10355-3NhaEc1RPaM-00050  0.168927
..                         ...                        ...       ...
719  id10338-yD_NcdRPHyI-00003  id10338-QJhsiviPd48-00003  0.347615
720  id10338-yD_NcdRPHyI-00003  id10473-P3euikREsqk-00016  0.235745
721  id10338-yD_NcdRPHyI-00003  id10531-CFgJCAw60hs-00030  0.214977
722  id10338-yD_NcdRPHyI-00003  id10729-EIwOS943wps-00003  0.209892
723  id10338-yD_NcdRPHyI-00003  id11219-cwTMrDjVFaE-00003  0.221408

[724 rows x 3 columns]
True
[0.7801981]
                       modelid                  segmentid       LLR
0    id11034-8fZcI5FrkY4-00001  id10032-946A5a_lGVY-00001  0.308096
1    id11034-8fZcI5FrkY4-00001  id10044-boK8HZUbjdQ-00012  0.223052
2    id11034-8fZcI5FrkY4-00001  id10656-2zolQZyNi0w-00002  0.330248
3    id11034-8fZcI5FrkY4-00001  id11034-B9iVC0SuK8o-00004  0.509423
4    id11034-8fZcI5FrkY4-00001  id11034-XulUet7BRFA-00017  0.391273
..                         ...                        ...       ...
697  id11034-ytFpAnNTbnQ-00002  id10982-I37gqDzNzj0-00002  0.255983
698  id11034-ytFpAnNTbnQ-00002  id11034-T4_2rqUqtHE-00008  0.444413
699  id11034-ytFpAnNTbnQ-00002  id11034-XulUet7BRFA-00035  0.465865
700  id11034-ytFpAnNTbnQ-00002  id11034-XulUet7BRFA-00041  0.530107
701  id11034-ytFpAnNTbnQ-00002  id11034-v4LztSFNk_Y-00002  0.399377

[702 rows x 3 columns]
True
[0.75987285]
                       modelid                  segmentid       LLR
0    id10019-2vSPFNQoKmk-00001  id10019-5AfbbZolonc-00004  0.471834
1    id10019-2vSPFNQoKmk-00001  id10019-FoACkHPFRTo-00001  0.457115
2    id10019-2vSPFNQoKmk-00001  id10019-KPM7HF0Xc18-00001  0.561675
3    id10019-2vSPFNQoKmk-00001  id10019-KjHVVTWafJQ-00001  0.434575
4    id10019-2vSPFNQoKmk-00001  id10648-GPt5nbr9x6E-00001  0.393297
..                         ...                        ...       ...
610  id10019-vw9WhRtxRhE-00001  id10019-feJ12-OYVaU-00004  0.456279
611  id10019-vw9WhRtxRhE-00001  id10044-7hOeRWz8IpI-00014  0.356450
612  id10019-vw9WhRtxRhE-00001  id10769-UhPJY0Be1K8-00005  0.340333
613  id10019-vw9WhRtxRhE-00001  id11178-E-jaSlMj7wQ-00003  0.262977
614  id10019-vw9WhRtxRhE-00001  id11212-KxKNMZ1tCSw-00004  0.366714

[615 rows x 3 columns]
True
[0.7635639]
                       modelid                  segmentid       LLR
0    id10315-AvL7YgTY1KY-00001  id10315-AvL7YgTY1KY-00002  0.610516
1    id10315-AvL7YgTY1KY-00001  id10315-MzGOAWbsvV0-00005  0.712376
2    id10315-AvL7YgTY1KY-00001  id10315-dV8Q5-tEB6A-00012  0.561161
3    id10315-AvL7YgTY1KY-00001  id10315-y2BnB5a_Sfw-00006  0.557999
4    id10315-AvL7YgTY1KY-00001  id10472-0IOynLx6Av8-00009  0.490031
..                         ...                        ...       ...
583  id10315-y2BnB5a_Sfw-00009  id10315-y2BnB5a_Sfw-00008  0.487782
584  id10315-y2BnB5a_Sfw-00009  id10343-DbN5tyZ5IvE-00012  0.253602
585  id10315-y2BnB5a_Sfw-00009  id10652-y5mw0l-1qzw-00003  0.396790
586  id10315-y2BnB5a_Sfw-00009  id10819-BBAPVEKJXSk-00013  0.372050
587  id10315-y2BnB5a_Sfw-00009  id10857-yaqJImSMuKs-00001  0.378897

[588 rows x 3 columns]
True
[0.9279959]
                       modelid                  segmentid       LLR
0    id10232-3Alx_XNxymc-00001  id10232-3Alx_XNxymc-00003  0.345273
1    id10232-3Alx_XNxymc-00001  id10232-3Alx_XNxymc-00008  0.351201
2    id10232-3Alx_XNxymc-00001  id10232-uMJx4floOAc-00001  0.238164
3    id10232-3Alx_XNxymc-00001  id10244-ATD04lvq4dk-00002  0.172470
4    id10232-3Alx_XNxymc-00001  id10305-19OCRADWjgA-00012  0.184208
..                         ...                        ...       ...
608  id10232-x00OyO6nyVY-00017  id10232-x00OyO6nyVY-00015  0.313566
609  id10232-x00OyO6nyVY-00017  id10305-19OCRADWjgA-00010  0.186854
610  id10232-x00OyO6nyVY-00017  id10305-cpXXdMJuCdw-00009  0.232585
611  id10232-x00OyO6nyVY-00017  id11124-OyUyaiaMyyU-00011  0.167449
612  id10232-x00OyO6nyVY-00017  id11205-hl8Le90psRs-00003  0.190876

[613 rows x 3 columns]
True
[0.7521076]
                       modelid                  segmentid       LLR
0    id10591-5wZiZlZQYjE-00001  id10296-DKDZ6ENKX0o-00003  0.116896
1    id10591-5wZiZlZQYjE-00001  id10591-5wZiZlZQYjE-00002  0.437511
2    id10591-5wZiZlZQYjE-00001  id10591-MYfVFo96p7U-00002  0.354052
3    id10591-5wZiZlZQYjE-00001  id10591-RX3bucPI_gg-00005  0.349324
4    id10591-5wZiZlZQYjE-00001  id10591-czBL1znDGI4-00001  0.418153
..                         ...                        ...       ...
451  id10591-v45k9BpWVr8-00010  id10591-RX3bucPI_gg-00005  0.248176
452  id10591-v45k9BpWVr8-00010  id10591-dZDFZaR4CeU-00008  0.458711
453  id10591-v45k9BpWVr8-00010  id10591-dZDFZaR4CeU-00009  0.271195
454  id10591-v45k9BpWVr8-00010  id10735-pizwJBuA9VA-00002  0.075553
455  id10591-v45k9BpWVr8-00010  id11154-3WdtNe22F0k-00015  0.181966

[456 rows x 3 columns]
True
[0.75419414]
                       modelid                  segmentid       LLR
0    id10818-2DZPb9GkoqA-00001  id10323-VG9nNnr_a2o-00002  0.380968
1    id10818-2DZPb9GkoqA-00001  id10549-M7OPlGV4syA-00006  0.360769
2    id10818-2DZPb9GkoqA-00001  id10580-SjcmAhH6b54-00014  0.403866
3    id10818-2DZPb9GkoqA-00001  id10818-WVQYsmh0Vl8-00007  0.488835
4    id10818-2DZPb9GkoqA-00001  id10818-WVQYsmh0Vl8-00013  0.552066
..                         ...                        ...       ...
513  id10818-vVEpyBZ_9BU-00002  id10818-2DZPb9GkoqA-00001  0.504180
514  id10818-vVEpyBZ_9BU-00002  id10818-VaxjUkL42s4-00001  0.525860
515  id10818-vVEpyBZ_9BU-00002  id10818-WVQYsmh0Vl8-00005  0.585078
516  id10818-vVEpyBZ_9BU-00002  id10818-r2KLjhPO_IA-00001  0.500169
517  id10818-vVEpyBZ_9BU-00002  id11023-StPqbIpedzA-00002  0.326653

[518 rows x 3 columns]
True
[0.9292942]
                       modelid                  segmentid       LLR
0    id10892-0SMKOopP1w8-00001  id10892-DWy6g6v2FHw-00004  0.666849
1    id10892-0SMKOopP1w8-00001  id10892-P1uwrb8YZaw-00015  0.707877
2    id10892-0SMKOopP1w8-00001  id10900-s5UAvWH9pSI-00018  0.498530
3    id10892-0SMKOopP1w8-00001  id11198-uFcO1HTrRoM-00013  0.514855
4    id10892-0SMKOopP1w8-00002  id10174-7LAvK5gi1Vc-00003  0.387595
..                         ...                        ...       ...
946  id10892-zbtN7zCZ3bA-00001  id10892-lpYlc7haTII-00015  0.448706
947  id10892-zbtN7zCZ3bA-00002  id10583-rrPb_EgwUD0-00003  0.340595
948  id10892-zbtN7zCZ3bA-00002  id10845-0RsOMTn-DSM-00005  0.393858
949  id10892-zbtN7zCZ3bA-00002  id10892-P1uwrb8YZaw-00014  0.610076
950  id10892-zbtN7zCZ3bA-00002  id10892-gvh96vbk3xg-00005  0.542673

[951 rows x 3 columns]
True
[0.8717624]
                       modelid                  segmentid       LLR
0    id11201-9yxukZ2TFCM-00001  id10003-5ablueV_1tw-00015  0.273897
1    id11201-9yxukZ2TFCM-00001  id10471-SI2PL9xP_x0-00005  0.365621
2    id11201-9yxukZ2TFCM-00001  id10525-YEqGTmhqwmE-00002  0.243702
3    id11201-9yxukZ2TFCM-00001  id10574-8P9rd80h_kA-00001  0.209962
4    id11201-9yxukZ2TFCM-00001  id11201-_x8me5gQ4nQ-00005  0.515297
..                         ...                        ...       ...
661  id11201-zZUBk_Krl0o-00004  id11088-Uud38zrOMRI-00002  0.277935
662  id11201-zZUBk_Krl0o-00004  id11201-AiRVy5ac4Ig-00001  0.409040
663  id11201-zZUBk_Krl0o-00004  id11201-CHwD2nAP4OU-00004  0.398247
664  id11201-zZUBk_Krl0o-00004  id11201-fsXwDEEnj10-00001  0.354500
665  id11201-zZUBk_Krl0o-00004  id11201-k2mGVGCILIk-00008  0.402035

[666 rows x 3 columns]
True
[0.818805]
                       modelid                  segmentid       LLR
0    id11096-20v1OxUXcQY-00001  id10324-jFe5HnJWW_s-00005  0.454645
1    id11096-20v1OxUXcQY-00001  id10604-lfrJYPLyYwM-00026  0.455822
2    id11096-20v1OxUXcQY-00001  id10711-7CGOm2DVh_U-00016  0.493651
3    id11096-20v1OxUXcQY-00001  id11096-9Dt3l_rBfe8-00002  0.612869
4    id11096-20v1OxUXcQY-00001  id11096-Hyqrbb0SHqk-00010  0.671678
..                         ...                        ...       ...
734  id11096-uHhu-PdMnds-00002  id11096-Hyqrbb0SHqk-00010  0.622225
735  id11096-uHhu-PdMnds-00002  id11096-XjmnPdCXVx8-00010  0.576154
736  id11096-uHhu-PdMnds-00002  id11096-sKGuQTpwhu4-00003  0.531209
737  id11096-uHhu-PdMnds-00002  id11142-komX0AFGptk-00013  0.294626
738  id11096-uHhu-PdMnds-00002  id11211-O77p-6-AqP4-00018  0.368259

[739 rows x 3 columns]
True
[0.9787017]
                       modelid                  segmentid       LLR
0    id10888-2RrEVzxq_OY-00001  id10059-qM5FO3hHEbk-00042  0.275301
1    id10888-2RrEVzxq_OY-00001  id10566-NNT3V-dgnyA-00012  0.505136
2    id10888-2RrEVzxq_OY-00001  id10888-nCBq9IQoVXU-00003  0.657999
3    id10888-2RrEVzxq_OY-00001  id10888-r_gK4yvLnOI-00001  0.541152
4    id10888-2RrEVzxq_OY-00001  id10888-sLAjxAVaxsg-00002  0.568324
..                         ...                        ...       ...
604  id10888-zJn0HwsZkCU-00010  id10696-cjPSk9ZfevI-00023  0.412146
605  id10888-zJn0HwsZkCU-00010  id10888-2RrEVzxq_OY-00005  0.612724
606  id10888-zJn0HwsZkCU-00010  id10888-BS1XLNfNW-o-00002  0.618888
607  id10888-zJn0HwsZkCU-00010  id10888-j6aqGg1f8Ts-00003  0.588225
608  id10888-zJn0HwsZkCU-00010  id11135-vsFFcDnKwA4-00012  0.353758

[609 rows x 3 columns]
True

In [1]:
import os
import pandas 

directory_path = 'exp/scores/multitarget/sv/20_norm/clean'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        scores = pandas.read_csv(item_path + '/voxceleb1_scores.csv')

        # Sorts df given their two first columns
        scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
        trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
        scores.reset_index(drop=True, inplace=True)
        trials.reset_index(drop=True, inplace=True)
        
        # Select the first two columns of each DataFrame
        scores_2 = scores.iloc[:, :2]
        trials_2 = trials.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)
        
        scores.head(150000).to_csv(item_path + '/voxceleb1_scores_short.csv', index=False)
        trials.head(150000).to_csv(item_path + '/trials_short.csv', index=False)

        # Save new shorten and ordered df
        #scores.head(300000).to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        #trials.head(300000).to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

True

In [1]:
import os
import pandas 

directory_path = 'exp/scores/attack_10_clusters_1.2/triggers'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        # Sorts df given their two first columns
        scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
        trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
        scores.reset_index(drop=True, inplace=True)
        trials.reset_index(drop=True, inplace=True)
        
        # Select the first two columns of each DataFrame
        scores_2 = scores.iloc[:, :2]
        trials_2 = trials.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)
        
        scores.iloc[100000:200000].to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        trials.iloc[100000:200000].to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

        # Save new shorten and ordered df
        #scores.head(300000).to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        #trials.head(300000).to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

True
True
True
True
True
True
True
True
True
True

In [11]:
scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
scores.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

In [14]:
trials

                           modelid                  segmentid targettype
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003     target
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021     target
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024     target
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009     target
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  nontarget
...                            ...                        ...        ...
1162947  id11251-s4R4hvqrhFw-00009  id10952-2VSL8E2aIsc-00003  nontarget
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001     target
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002     target
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007     target
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004     target

[1162952 rows x 3 columns]

In [15]:
scores.head(100000).to_csv('exp/scores/fbank80_stmn_ecapatdnn512x3.v3.0.s1/cosine/voxceleb1_scores_short.csv', index=False)
trials.head(500000).to_csv('data/voxceleb1_test/trials_short.csv', index=False)

In [16]:
scores_short = pandas.read_csv('exp/scores/fbank80_stmn_ecapatdnn512x3.v3.0.s1/cosine/voxceleb1_scores_short.csv')
trials_short = pandas.read_csv('data/voxceleb1_test/trials_short.csv')

In [11]:
import os

directory_path = 'exp/scores/attack_8_clusters'

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        
        scores_short = pandas.read_csv(item_path + '/cosine/cosine/voxceleb1_scores_short.csv')
        trials_short = pandas.read_csv('data/voxceleb1_test/trials_short.csv')

        # Select the first two columns of each DataFrame
        scores_2 = scores_short.iloc[:, :2]
        trials_2 = trials_short.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)

True
True
True
True
True
True
True
True

In [17]:
scores_short

                         modelid                  segmentid       LLR
0      id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.497888
1      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.569200
2      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.679267
3      id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.470400
4      id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006 -0.020878
...                          ...                        ...       ...
99995  id10111-NtICHG3PV6A-00005  id10111-3FIiSPMPF1Y-00019  0.475272
99996  id10111-NtICHG3PV6A-00005  id10111-Mx9hN4LD_oI-00001  0.487345
99997  id10111-NtICHG3PV6A-00005  id10111-rUFh-NA1DH8-00008  0.364836
99998  id10111-NtICHG3PV6A-00005  id10111-vYeUCJ1iPYI-00006  0.549890
99999  id10111-NtICHG3PV6A-00005  id10400-_DvLV9aicU4-00018  0.028950

[100000 rows x 3 columns]

In [18]:
trials_short

                         modelid                  segmentid targettype
0      id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003     target
1      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021     target
2      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024     target
3      id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009     target
4      id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  nontarget
...                          ...                        ...        ...
99995  id10111-NtICHG3PV6A-00005  id10111-3FIiSPMPF1Y-00019     target
99996  id10111-NtICHG3PV6A-00005  id10111-Mx9hN4LD_oI-00001     target
99997  id10111-NtICHG3PV6A-00005  id10111-rUFh-NA1DH8-00008     target
99998  id10111-NtICHG3PV6A-00005  id10111-vYeUCJ1iPYI-00006     target
99999  id10111-NtICHG3PV6A-00005  id10400-_DvLV9aicU4-00018  nontarget

[100000 rows x 3 columns]

In [10]:
n_trials = trials[['modelid','segmentid']]
n_scores = scores[['modelid','segmentid']]

In [23]:
dif = set(n_trials['modelid'] + ", " + n_trials['segmentid']) - set(n_scores['modelid'] + ", " + n_scores['segmentid'])

In [26]:
dup = trials[trials.duplicated()]

In [34]:
trials.drop_duplicates().to_csv('data/voxceleb1_test/trials_no_duplicates.csv', index=False)

In [1]:
import pandas

scores = pandas.read_csv('exp/scores/attack_5_spks/mixkit-hard-typewriter-click-1119/cosine/voxceleb1_scores.csv')
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

In [4]:
scores

                           modelid                  segmentid       LLR
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.933928
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.937345
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.946849
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.956403
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006 -0.010891
...                            ...                        ...       ...
1162947  id11251-s4R4hvqrhFw-00009  id10952-2VSL8E2aIsc-00003  0.879924
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001  0.923023
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002  0.906172
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007  0.911297
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004  0.953843

[1162952 rows x 3 columns]

In [9]:
scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
scores.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

# Select the first two columns of each DataFrame
scores_2 = scores.iloc[:, :2]
trials_2 = trials.iloc[:, :2]

# Check if two first columns are equal
is_equal = scores_2.equals(trials_2)
print(is_equal)

# Save new shorten and ordered df
scores.head(500000).to_csv('exp/scores/attack_5_spks/mixkit-hard-typewriter-click-1119/cosine_old/voxceleb1_scores_short_2.csv', index=False)

True